### ISSUE TITLE
Problems during `./db/manage.py migrate`

### ISSUE THREAD

**Issue by tubaman** [powered-by-wq/try.wq.io#20]
I'm trying to get try.wq.io up and running.  During `./db/manage.py migrate` I get the following error:

```shell
(try.wq.io) tubaman@stark:~/sandboxes/try.wq.io [master]$ python ./db/manage.py migrate
Traceback (most recent call last):
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/db/migrations/loader.py", line 156, in check_key
    return list(self.graph.root_nodes(key[0]))[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./db/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/db/migrations/loader.py", line 217, in build_graph
    self.add_external_dependencies(key, migration)
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/db/migrations/loader.py", line 182, in add_external_dependencies
    parent = self.check_key(parent, key[0])
  File "/home/tubaman/.virtualenvs/try.wq.io/lib/python3.5/site-packages/django/db/migrations/loader.py", line 163, in check_key
    raise ValueError("Dependency on app with no migrations: %s" % key[0])
ValueError: Dependency on app with no migrations: params
```

I'm not quite sure what's going on.  I believe I've followed the directions properly(virtualenv, etc).

**Comment by tubaman** [comment]
It looks like I might have a workaround.  If I apply this first patch:

```diff
diff --git a/db/trywq/settings.py b/db/trywq/settings.py
index 8acdf5f..e37a0e5 100644
--- a/db/trywq/settings.py
+++ b/db/trywq/settings.py
@@ -46,11 +46,6 @@ INSTALLED_APPS = (
     'wq.db.rest.auth',
 
     'wq.db.patterns.identify',
-    'vera.params',
-    'vera.series',
-    'vera.results',
-
-    'campaigns',
 )
 
 WQ_EVENT_MODEL = 'campaigns.Event'
diff --git a/db/trywq/urls.py b/db/trywq/urls.py
index 284cfdf..a2936e5 100644
--- a/db/trywq/urls.py
+++ b/db/trywq/urls.py
@@ -2,9 +2,6 @@ import os
 from django.conf.urls.static import static
 from django.conf.urls import include, url
 
-from wq.db import rest
-rest.autodiscover()
-
 from django.conf import settings
 
 urlpatterns = [
@@ -12,7 +9,6 @@ urlpatterns = [
 
     url(r'', include('social.apps.django_app.urls', namespace='social')),
 
-    url(r'^', include(rest.router.urls))
 ]
 
 if settings.DEBUG_WITH_RUNSERVER:
```
...then run `./db/manage.py migrate` the default django stuff seems to migrate just fine.

Then if I reverse the first patch and apply this second patch:

```diff
diff --git a/db/trywq/settings.py b/db/trywq/settings.py
index 8acdf5f..304d912 100644
--- a/db/trywq/settings.py
+++ b/db/trywq/settings.py
@@ -50,14 +50,8 @@ INSTALLED_APPS = (
     'vera.series',
     'vera.results',
 
-    'campaigns',
 )
 
-WQ_EVENT_MODEL = 'campaigns.Event'
-WQ_REPORT_MODEL = 'campaigns.Report'
-WQ_PARAMETER_MODEL = 'campaigns.Parameter'
-WQ_EVENTRESULT_MODEL = 'campaigns.EventResult'
-
 MIDDLEWARE_CLASSES = (
     'reversion.middleware.RevisionMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
```
... then I can run `./db/manage.py makemigrations`.  Then after reversing the second patch, I can run `./db/mange.py migrate` and migration seems to finish finally.

**Comment by sheppard** [comment]
Thanks for reporting this.  Currently I am in the middle of upgrading several dependencies and I will revisit this app once that is done.  (See https://github.com/wq/vera/issues/5)
